version: "3.9"
services:
  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: shavtzakon
      POSTGRES_PASSWORD: rbs1995
      POSTGRES_DB: db

    ports:
      - "5432:5432"
    volumes:
      - db:/var/lib/posgressql

volumes:
  db:
